server:
  port: 8091

spring:
  thymeleaf:
    cache : false

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://ec2-mysql-db1.cy1giep8fwh3.ap-northeast-2.rds.amazonaws.com:3306/bootex

    username: admin
    password: mydbpassword

  jpa:
    #    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    #    open-in-view: false
    show-sql: true
    hibernate:
      format_sql: true
      ddl-auto: update

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE