server:
  port: 8091

spring:
  thymeleaf:
    cache : false

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://RDSDB:3306/bootex

    username: mysqlID
    password: mysqlPW

  jpa:
    #    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    #    open-in-view: false
    show-sql: true
    hibernate:
      format_sql: true
      ddl-auto: create

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE